//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Build
    {
        public int Number_of_build { get; set; }
        public Nullable<int> Number_of_district_build { get; set; }
        public Nullable<int> Name_of_goods_build { get; set; }
        public string Name_of_hardware { get; set; }
        public string Name_of_furniture { get; set; }
        public Nullable<int> Quantity_of_hardware { get; set; }
        public Nullable<int> Quantity_of_furniture { get; set; }
    
        public virtual Goods Goods { get; set; }
    }
}
