//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checking
    {
        public int Number_of_checking { get; set; }
        public Nullable<int> Part_of_checking { get; set; }
        public Nullable<int> Goods_of_checking { get; set; }
        public Nullable<int> Products_of_checking { get; set; }
        public Nullable<int> GOST_of_checking { get; set; }
    
        public virtual Goods Goods { get; set; }
        public virtual Parts Parts { get; set; }
        public virtual Products Products { get; set; }
    }
}
