//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coating
    {
        public int id_coating { get; set; }
        public Nullable<int> Number_of_district_coating { get; set; }
        public Nullable<int> Name_of_product_coating { get; set; }
        public Nullable<int> Quantity_of_coating { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
