//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Number_of_employee { get; set; }
        public string Employee_last_name { get; set; }
        public string Employee_first_name { get; set; }
        public string Employee_second_name { get; set; }
        public Nullable<System.DateTime> Employee_date_of_birth { get; set; }
        public string Employee_passport { get; set; }
        public string Employee_address { get; set; }
        public string Employee_telephone { get; set; }
    }
}
