//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int id_material { get; set; }
        public string Name_of_material { get; set; }
        public string Units_of_measure { get; set; }
        public Nullable<int> Quantity_of_material { get; set; }
        public Nullable<System.DateTime> Warranty_of_material { get; set; }
        public Nullable<int> Cost_of_material { get; set; }
    }
}
