//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Number_of_order { get; set; }
        public Nullable<int> Name_of_production_order { get; set; }
        public Nullable<int> Quantity_of_order { get; set; }
        public Nullable<System.DateTime> Date_of_order { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
