//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Realisation
    {
        public int Number_of_realisation { get; set; }
        public Nullable<int> Volume_of_realisation { get; set; }
        public Nullable<System.DateTime> Date_of_realisation { get; set; }
        public string Type_of_realisation { get; set; }
        public Nullable<int> Number_of_issue_realisation { get; set; }
        public Nullable<int> Unit_of_price_realisation { get; set; }
    }
}
