//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int id_supplier { get; set; }
        public Nullable<int> Volume_of_supply { get; set; }
        public Nullable<System.DateTime> Date_of_supply { get; set; }
        public string Name_of_supply { get; set; }
        public string Name_of_supplier { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
    }
}
