//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshop
    {
        public int id_workshop { get; set; }
        public string Name_workshop { get; set; }
        public Nullable<int> Number_of_district_workshop { get; set; }
        public Nullable<int> Code_of_equipment_workshop { get; set; }
    }
}
